InventoryGenie/Controllers/LoginController.cs
using InventoryGenie.Data;
using InventoryGenie.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryGenie.Controllers
{
    public class LoginController : Controller
    {
        //move database context to Employee so that employee can manipulate database
        public LoginController(ApplicationDbContext ctx)
        {
            Employee.Context = ctx;
        }

        //default action called in Login Controller
        // it will make new employee object to prompt employee to enter username and password
        // other fields are not necessary
        [HttpGet]
        public IActionResult Index()
        {
            return View(new Employee());
        }


        //after employee enter username and password inside Index view
        //it comes back to here employee holds username and password only. other field are empty
        [HttpPost]
        public IActionResult Login(Employee employee)
        {
            //will search for employee with the same username and password, and save it in LoggedInEmployee if not found it saves null
            Employee.Login(employee.UserName, employee.Password);
            
            if (Employee.LoggedInEmployee == null)//if LoggedInEmployee is null it means employee
                                                  //was not found then it's incorrect username and password
            {
                //clears form
                ModelState.Clear();

                //stores Msg to show this message in Login View
                ViewBag.Msg = "Incorrect Username/password";

                //direct employee to Login page so the employee tries again
                return View("Index");
            }
            else //if employee was found
            {
                if (Employee.LoggedInEmployee.IsTemporaryPassword == true) //if employee needs to change password
                                                                           //it directs employee to ChangePassword
                {
                    return View("ChangePassword", Employee.LoggedInEmployee);
                }
                //if employee doesn't need to change password then empoloyee will be directed to Home page
                return RedirectToAction("Index", "Home");
            }
            
        }

        //this will prompt employee to ChangePassword View
        [HttpGet]
        public IActionResult ChangePassword(Employee LoggedInEmployee)
        {
            return View(LoggedInEmployee);
        }

        //Post method it brings back from ChangePassword View employee(username, (old)password, and ID),
        //new password and Confirmed new password
        [HttpPost]
        public IActionResult ChangePassword(Employee LoggedInEmployee, string newPassword, string confirmedNewPassword)
        {

            //change password if all fields are ok, if not, it returns a message 
            ViewBag.Msg = Employee.ChangePassword(LoggedInEmployee.EmployeeID, newPassword, confirmedNewPassword);
            
            //if password fields are not ok because not null msg means there is something wrong with the fields
            if (ViewBag.Msg != null)
            {
                //open the same page again for another try
                return View("ChangePassword", LoggedInEmployee);
            }

            //if sucessful in changing the password. employee will be logged in
            //and go to home page( index get)
            return RedirectToAction("Index", "Home");
        }


        //logs current employee out
        [HttpGet]
        public IActionResult LogOut()
        {
            //clear logged in employee data
            Employee.Logout();
            //return to Login page
            return View("Index");
        }
        

    }
}

InventoryGenie/Controllers/OrderController.cs
using InventoryGenie.Data;
using InventoryGenie.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryGenie.Controllers
{

    //Order Controller to place and receive orders
    //only General Manager and Warehouse leaders have access to this
    //Everyone else will be directed to home
    public class OrderController : Controller
    {
        //search text will be blank and Sortby will be by Date & Time once Index page is opened.
        //after that, once the user search one time, SearchText and Sortby will be changed. To open the page again with the same
        //query result
        private static string? SearchText;
        private static string? SortBy;

        //this is used for PlaceOrderView. It helps to show products that needs to be ordered which are the ones below minimum level 
        private static bool ShowOnlyBelowMinimumLevel =true;

        //These are orderby options in the Orders Records page
        //This page will allow employee to receive the orders and view order details 
        readonly string[] OrderRecordSortByOptions =
        {
            "Date & Time",
            "Product",
            "Category",
            "Supplier",
        };

        //These are orderby options in the Place Order View.
        readonly string[] ProductSortByOptions =
        {
            "Product ID",
            "Product Name",
        };

        //pass database context to Employee, so employee can manipulate it
        public OrderController(ApplicationDbContext ctx)
        {
            Employee.Context = ctx;
        }



        [HttpGet]
        public IActionResult Index()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            // sets sortby to the default Date & Time and searchText null
            // This will return all order Records sorted from the newest to the oldest
            SortBy = "Date & Time";
            SearchText = null;
            // redirect to Search method [HttpGet]
            return RedirectToAction("Search");
        }


        //After searchText and sortBy was posted from Index View it saves them in the static SortBy and SearchText
        [HttpPost]
        public IActionResult Search(string searchText, string sortBy)
        {

            SortBy = sortBy;
            SearchText = searchText;
            // redirect to Search method [HttpGet]
            return RedirectToAction("Search");

        }

        //It Gets list of orders Records based on the static SearchBy and SortBy
        //and view it in Index View
        [HttpGet]
        public IActionResult Search()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            ViewBag.SortByOptions = OrderRecordSortByOptions;
            List<OrderRecord> orderRecords = Employee.LoggedInEmployee.SearchOrderRecords(SortBy, SearchText);
            ViewBag.SortBy = SortBy;
            ViewBag.SearchText = SearchText;
            return View("Index", orderRecords);
        }

        [HttpGet]
        public IActionResult Receive(int orderRecordId)
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");


            OrderRecord orderRecord = Employee.LoggedInEmployee.GetOrderRecordByID(orderRecordId);
            ViewBag.Action = "Confirm";
            return View("Details",orderRecord);
        }

        [HttpPost]
        public IActionResult Receive(OrderRecord orderRecord)
        {
            Employee.LoggedInEmployee.ReceiveOrder(orderRecord);
            return RedirectToAction("Search");
        }

        [HttpGet]
        public IActionResult Details(int orderRecordId)
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            ViewBag.Action = "Details";
            // Gets details of an order and show the detals in Details View
            OrderRecord orderRecord = Employee.LoggedInEmployee.GetOrderRecordByID(orderRecordId);
            return View("Details",orderRecord);
        }


        [HttpGet]
        public IActionResult PlaceOrderView()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            //sets the static SortBy, SearchText, and ShowOnlyBelowMinimumLevel to their default values
            SortBy = "Product ID";
            SearchText = null;
            ShowOnlyBelowMinimumLevel = true;
            return RedirectToAction("SearchProduct");
            
        }


        //This will receive the posted searchText, sortBy, and showOnlyBelowMinimumLevel,
        //and save their content into their static equivelent 
        [HttpPost]
        public IActionResult SearchProduct(string searchText, string sortBy,bool showOnlyBelowMinimumLevel)
        {

            SortBy = sortBy;
            SearchText = searchText;
            ShowOnlyBelowMinimumLevel=showOnlyBelowMinimumLevel;
            return RedirectToAction("SearchProduct");

        }

        [HttpGet]
        public IActionResult SearchProduct()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            //prepare viewbag for sort by select menu and the check box show only below minimum level
            ViewBag.SortByOptions = ProductSortByOptions;
            ViewBag.ShowOnlyBelowMinimumLevel = ShowOnlyBelowMinimumLevel;

            //Gets products list searched by SearchText, sorted by SortBy and will take ShowOnlyBelowMinimumLevel value in consideration
            List<Product> products = 
                Employee.LoggedInEmployee.OrderManagementSearchProducts(SortBy, SearchText,ShowOnlyBelowMinimumLevel);

            //Gets Totsl Quantity Not Received yet for each product that resulted from the previous query.
            //This will help in placing orders to take these in consideration and will help in deciding Recommended Quantity to Order
            List<int> QuantityNotReceivedCount = new List<int>();
            foreach (Product product in products)
            {
                QuantityNotReceivedCount.Add(Employee.LoggedInEmployee.GetQuantityNotReceivedForProduct(product.Name));
            }
            ViewBag.QuantityNotReceivedCount = QuantityNotReceivedCount;
            ViewBag.SortBy = SortBy;
            ViewBag.SearchText = SearchText;
            return View("PlaceOrderView", products);
        }


        [HttpPost]
        public IActionResult PlaceOrder(int productID, int orderQuantity)
        {
            // This will create Order Record in Data base
            Employee.LoggedInEmployee.PlaceOrder(productID, orderQuantity);
            return RedirectToAction("SearchProduct");

        }

        // if the LoggedInEmployee is not null and role is GM (1) or WL(2) then return true.
        // if it's not true then user will be redirected to Home.
        // Home will redirect to login if there is no logged in Employee. 
        private static bool IsAuthenticatedAndAuthorized()
        {
            return Employee.LoggedInEmployee != null && (Employee.LoggedInEmployee.RoleId == 1 || Employee.LoggedInEmployee.RoleId == 2);
        }

    }
}

InventoryGenie/Controllers/SalesController.cs
using InventoryGenie.Data;
using InventoryGenie.Models;
using Microsoft.AspNetCore.Mvc;

namespace InventoryGenie.Controllers
{
    public class SalesController : Controller
    {
        private static string? SearchText;
        private static string? SortBy;

        //these hold the items in the cart and the quantity of the product in the cart
        //cart is emptied after checkout or return, or at logout  
        public static Dictionary<int, int> Cart = new();
        public static List<Product> ProductsInCart =new();

        readonly string[] sortByOptions =
        {
            "Product ID",
            "Name",
            "Category",
            "Supplier",
            "Shelf Price"
        };

        //gives DbContext to Employee
        public SalesController(ApplicationDbContext ctx)
        {
            Employee.Context = ctx;
        }

        //first function to be called in this controller
        [HttpGet]
        public IActionResult Index()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            //The default settings for sortby and searchtext
            SortBy = "Product ID";
            SearchText = null;

            //after getting default settings set up redirect to HttpGet Search to show all products in Index view 
            return RedirectToAction("Search");
            
        }


        [HttpPost]
        public IActionResult Search(string searchText, string sortBy)
        {
            SortBy = sortBy;
            SearchText = searchText;
            return RedirectToAction("Search");

        }
        [HttpGet]
        public IActionResult Search()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            ViewBag.SortByOptions = sortByOptions;
            List<Product> products =
                Employee.LoggedInEmployee.SalesManagementSearchProducts(SortBy, SearchText);
            ViewBag.SortBy = SortBy;
            ViewBag.SearchText = SearchText;
            return View("Index", new Tuple<List<Product>, Dictionary<int, int>>(products, Cart));
        }

        [HttpGet]
        public IActionResult ClearCart()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");
            Cart = new();
            ProductsInCart = new();

            return RedirectToAction("Search");
        }

        [HttpPost]
        public IActionResult AddToCart(int productID, int quantityToBeAddedToCart)
        {

            if (!Cart.ContainsKey(productID))
            {
                Cart.Add(productID, quantityToBeAddedToCart);
                ProductsInCart.Add(Employee.LoggedInEmployee.GetProductByID(productID));
            }
            else
                Cart[productID] += quantityToBeAddedToCart;

            return RedirectToAction("Search");
        }

        [HttpGet]
        public IActionResult ViewCart()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            return View(new Tuple<List<Product>,Dictionary<int,int>>(ProductsInCart, Cart));
        }

        [HttpPost]
        public IActionResult UpdateCart(int productID,int changeQuantityInCart)
        {
            Cart[productID] = changeQuantityInCart;
            return View("ViewCart", new Tuple<List<Product>, Dictionary<int, int>>(ProductsInCart, Cart));
        }

        [HttpGet]
        public IActionResult CheckOut()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            Employee.LoggedInEmployee.CheckOut(ProductsInCart,Cart);
            ProductsInCart = new ();
            Cart = new();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Return()
        {
            if (!IsAuthenticatedAndAuthorized())
                return RedirectToAction("Index", "Home");

            Employee.LoggedInEmployee.Return(ProductsInCart, Cart);
            ProductsInCart = new();
            Cart = new();
            return RedirectToAction("Index");
        }
        // if the LoggedInEmployee is not null and role is GM (1) or WL(2) or Assocaite(3) then return true.
        // if it's not true then user will be redirected to Home.
        // Home will redirect to login if there is no logged in Employee. 
        private static bool IsAuthenticatedAndAuthorized()
        {
            return Employee.LoggedInEmployee != null && (Employee.LoggedInEmployee.RoleId == 1 ||
                Employee.LoggedInEmployee.RoleId == 2 || Employee.LoggedInEmployee.RoleId == 3);
        }
    }
}

InventoryGenie/Views/Shared/_Layout.cshtml
@{
    if (Employee.LoggedInEmployee != null)
    {
        ViewBag.Role = Employee.LoggedInEmployee.RoleId;
    }
    else
    {
        ViewBag.Role = 0;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory Genie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventoryGenie.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css" integrity="sha-long-hash_code" crossorigin="anonymous">
</head>
<body>
    <header>
        <div class="header-left">
            <i class="fa-sharp fa-solid fa-database"></i>
            <a class="logo navbar-brand fa fa-regular">Inventory Genie</a>
            <input type="checkbox" id="nav_check" hidden />
            <nav>
                    <i class="logo fa-sharp fa-solid fa-database"></i>
                    <a class="logo navbar-brand fa fa-regular">Inventory Genie</a>

                    <ul>

                        @if (ViewBag.Role == 1 || ViewBag.Role == 2 || ViewBag.Role == 3)
                        {
                            <li class="nav-item">
                                <a class="active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        @if (ViewBag.Role == 1)
                        {
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                            </li>
                        }
                        @if (ViewBag.Role == 1 || ViewBag.Role == 2)
                        {
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Supplier" asp-action="Index">Suppliers</a>
                            </li>
                        }
                        @if (ViewBag.Role == 1 || ViewBag.Role == 2)
                        {
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                            </li>
                        }
                        @if (ViewBag.Role == 1 || ViewBag.Role == 2 || ViewBag.Role == 3)
                        {
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Stock" asp-action="Index">Stocks</a>
                            </li>
                        }
                        @if (ViewBag.Role == 1 || ViewBag.Role == 2)
                        {
                            <li class="nav-item">
                                <a class="" asp-area="" asp-controller="Reporting" asp-action="Index">Reports</a>
                            </li>
                        }
                        @if (ViewBag.Role == 1 || ViewBag.Role == 2 || ViewBag.Role == 3)
                        {
                            <li class="nav-item">
                                <a class="" asp-area="" asp-controller="Sales" asp-action="Index">Sales</a>
                            </li>
                        }
                        @if (ViewBag.Role == 1 || ViewBag.Role == 2)
                        {
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                            </li>
                        }
                        @if (ViewBag.Role != 0)
                        {
                            <li class="logout-btn-burger">
                                <a class="btn btn-outline-primary fa-solid fa-text" asp-area="" asp-controller="Login" asp-action="LogOut">Log Out&nbsp;<i class="fa fa-sign-out"></i></a>
                            </li>
                        }
                    </ul>
            </nav>
        </div>
        <div class="header-right">
            <ul>
                @if (ViewBag.Role != 0)
                {
                    <li class="logout-btn-right">
                        <a class="btn btn-outline-primary fa-solid fa-text" asp-area="" asp-controller="Login" asp-action="LogOut">Log Out&nbsp;<i class="fa fa-sign-out"></i></a>
                    </li>
                }
            </ul>
            <div class="hamburger">
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </header>
    <!-- Script to activate the hamburger menu when resizing screen. -->
    <script>
        hamburger = document.querySelector(".hamburger");
        nav = document.querySelector("nav");
        hamburger.onclick = function () {
            nav.classList.toggle("active");
        };
    </script>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - InventoryGenie
        </div>
    </footer>
    <script type="module"
            src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule
            src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- Set navbar elements to active when selected. -->
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            document.querySelectorAll('.nav-item a').forEach(link => {
                if (link.getAttribute('href').toLowerCase() === location.pathname.toLowerCase()) {
                    link.classList.add('active');
                }
                else if (link.getAttribute('href').toLowerCase() + "search/" === location.pathname.toLowerCase()) {
                    link.classList.add('active');
                }
                else {
                    link.classList.remove('active');
                }
            });
        })
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>